# パスを可視化するかの設定用
is_visible: true

# 制御周波数 [Hz]
hz: ######

# frame_id
robot_frame: "base_link"

# 速度制限
max_vel1: ######            # [m/s]（平常時）
max_vel2: ######             # [m/s]（減速時）
avoid_thres_vel: ######     # [m/s]（回避中か判断する閾値）
min_vel: ######              # [m/s]
max_yawrate1: ######         # [rad/s]（平常時）
max_yawrate2: ######        # [rad/s]（減速時）
turn_thres_yawrate: ######  # [rad/s]（旋回中か判断する閾値）
mode_log_time: ######

# 加速度制限
max_accel: ######    # [m/s^2]
max_dyawrate: ###### # [rad/s^2]

# 速度解像度
vel_reso: ######    # [m/s]
yawrate_reso: ###### # [rad/s]

# 停止状態か判断する閾値
stop_vel_th: ######
stop_yawrate_th: ######

# 時間 [s]
dt: ######
predict_time1: ######
predict_time2: ######

# 機体サイズ(半径) [m]
roomba_radius: ######
radius_margin1: ######  #（平常時）
radius_margin2: ###### #（減速時）

# 重み定数 [-]
weight_heading1: ###### #（平常時）
weight_heading2: ######  #（減速時）
weight_dist1: ######     #（平常時）
weight_dist2: ######     #（減速時）
weight_vel: ######

# 許容誤差 [m]
goal_tolerance: ######

# 評価関数distで探索する範囲 [m]
search_range: ######