name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ros:humble-ros-core
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup ROS
        uses: ros-tooling/setup-ros@v0.7
      - name: Build
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          target-ros2-distro: humble
